// <auto-generated />
using app.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace app.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171127014540_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("app.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessId");

                    b.Property<string>("City");

                    b.Property<string>("Code");

                    b.Property<double>("Cost");

                    b.Property<string>("CostDescription");

                    b.Property<string>("Detail");

                    b.Property<string>("Disclaimer");

                    b.Property<DateTime>("Expiration");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsSponsored");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("State");

                    b.Property<string>("StreetAddress");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.ToTable("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
